import Head from "next/head";
import Image from "next/image";
// import { Inter } from '@next/font/google'
import styles from "../styles/Home.module.css";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
// import Navbar from './component/Navbar';
import Main from "./component/Main";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import Cursor from "./component/Cursor";

// const inter = Inter({ subsets: ['latin'] })
const theme = createTheme({
  palette: {
    primary: {
      main: "#0A1929",
    },
  },
});

export default function Home() {
  return (
    <>
      <ThemeProvider theme={theme}>
        <Head>
          <title>MD.AL-AMIN | Web Developer</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Cursor />
          {/* <Navbar/> */}
          <Main />
        </main>
        <footer>
          <Typography>Footer</Typography>
        </footer>
      </ThemeProvider>
    </>
  );
}
